# Generated by Django 5.1.7 on 2025-04-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('production_expert', 'Production Expert'), ('regular_staff', 'Regular Staff')], default='regular_staff', max_length=20),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_customised',
            new_name='is_customized',
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='is_customised',
            new_name='is_customized',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='toy',
            name='customized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toys_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='toy',
            name='specification',
            field=models.TextField(blank=True, help_text='Custom specifications for the toy', null=True),
        ),
        migrations.AddField(
            model_name='usercontactdetail',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.TextField(blank=True, help_text='Custom specifications for the order', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('customer', 'Customer'), ('administrator', 'Administrator'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='StaffType',
        ),
    ]
