# Generated by Django 5.1.7 on 2025-04-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userrole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreport',
            name='order',
        ),
        migrations.AddField(
            model_name='productionreport',
            name='toy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.toy'),
        ),
    ]
