# Generated by Django 5.1.7 on 2025-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productionreport_order_productionreport_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
