# Generated by Django 5.1.7 on 2025-04-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productionreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
