# Generated by Django 5.1.7 on 2025-04-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toy_reviews', to='core.toy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
